### ISSUE TITLE
Update proxyUrl docs to mention HTTPS is fine and to also talk about the env vars you can set

### ISSUE THREAD

**Issue by zionts** [apollographql/engine-docs#171] opened 2018-05-18 02:07 UTC

**Comment by qubusp** [comment] 2018-05-18 11:12
Same problem here - trying to fine tune proxy engine on local and fine tune stuff - not able to parse 
env 

```
version: '3.3'
services:
  boom:
    image: gcr.io/mdg-public/engine:1.0.6
    env_file:
      - ./env
    links:
      - nginx
  nginx:
    image: interceptor
    ports:
      - 80:80

```

**Comment by daniman** [comment] 2018-05-22 21:00
This is a duplicate of #173, closing in favor of that issue.

**Closed by daniman** 2018-05-22 21:00 UTC
